- name: Create PUA LDAP Virtual Server and DNS
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get Scope
      include_role:
        name: nextdhcpaddr
      vars:
        vs_name: webtop_address
        dhcp_scope: 10.1.10.96


